### ISSUE TITLE
Add Owners as Maintainers for SCITT-API-Emulator repo

### ISSUE THREAD

**Issue by kkarunakaran89** [scitt-community/scitt-api-emulator#11]
https://github.com/scitt-community/scitt-api-emulator/blob/main/OWNERS to be added as maintenance members for the repo. I have a PR out for traceability

https://github.com/kkarunakaran89/scitt-api-emulator/pull/3

**Comment by SteveLasker** [comment]
This is a tracing item to complete the configuration of the OWNERS added to the GitHub Team: [scitt-api-emulator-maintainers](https://github.com/orgs/scitt-community/teams/scitt-api-emulator-maintainers/members)

This is now complete
